<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPlh5wpv\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPlh5wpv/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPlh5wpv.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerPlh5wpv\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerPlh5wpv\EccubeProdProjectContainer([
    'container.build_hash' => 'Plh5wpv',
    'container.build_id' => 'a9bc4068',
    'container.build_time' => 1617511186,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPlh5wpv');
