<?php

namespace Plugin\StockShow4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\StockShow4\Entity\StockShowConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * StockShowConfigRepository
 * このRepositoryはEntityのfetch(読み込み)を補助するためのクラス
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

// EC-CUBE本体のAbstractRepositoryを継承しています。
// AbstractRepositoryはServiceEntityRepositoryを継承しています。
class StockShowConfigRepository extends AbstractRepository
{
    /**
     * StockShowConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, StockShowConfig::class);
    }

    /**
     * エンティティのidを指定し、一致するレコードをオブジェクトで返す
     *
     * @param int $id
     * @return null|StockShowConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

}
